-- =========================================================
-- Products table
-- =========================================================
CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    price DECIMAL(12,2) NOT NULL,
    stock_quantity INT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

-- Index to speed up product searches by name (catalog / search use cases)
-- Useful for LIKE queries and filtering in product listings
CREATE INDEX idx_products_name
    ON products(name);

-- =========================================================
-- Orders table
-- =========================================================
CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_name VARCHAR(100) NOT NULL,
    customer_email VARCHAR(100) NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

-- Index to efficiently filter orders by status
-- Common in dashboards, admin panels, and order processing flows
CREATE INDEX idx_orders_status
    ON orders(status);

-- Index to quickly retrieve orders by customer email
-- Used in customer history lookups and support scenarios
CREATE INDEX idx_orders_customer_email
    ON orders(customer_email);

-- =========================================================
-- Order items table
-- =========================================================
CREATE TABLE order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    quantity INT NOT NULL,
    unit_price DECIMAL(10,2) NOT NULL,
    subtotal DECIMAL(10,2) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,

    CONSTRAINT fk_order
        FOREIGN KEY (order_id) REFERENCES orders(id),

    CONSTRAINT fk_product
        FOREIGN KEY (product_id) REFERENCES products(id)
);

-- Index to efficiently retrieve all items belonging to a specific order
-- Critical for order details, deletes, and JOINs between orders and order_items
CREATE INDEX idx_order_items_order_id
    ON order_items(order_id);

-- Index to improve performance when accessing order items by product
-- Useful for validations, reporting, and JOINs with products
CREATE INDEX idx_order_items_product_id
    ON order_items(product_id);

-- Unique index to prevent duplicate products within the same order
-- Ensures data integrity and simplifies business logic
CREATE UNIQUE INDEX ux_order_items_order_product
    ON order_items(order_id, product_id);
